const { env } = process;
const PORT = env.PORT || 3000;

const AWS_REGION = env.AWS_REGION || 'us-east-1';
const AWS_ACCESS_KEY_ID = env.AWS_ACCESS_KEY_ID;
const AWS_SECRET_ACCESS_KEY = env.AWS_SECRET_ACCESS_KEY;
const AWS_ASSUME_ROLE_ARN = env.AWS_ASSUME_ROLE_ARN;

const AUTO_DESTROY_INACTIVITY_THRESHOLD_MIN = env.AUTO_DESTROY_INACTIVITY_THRESHOLD_MIN || 30;

const AUTH_URL = env.AUTH_URL || 'https://auth.eng.bellwether.link';
const AUTH_APP_CLIENT_ID = env.AUTH_APP_CLIENT_ID || 'vkpruk2fpkbg15a750qlb5ve5';
const AUTH_APP_CLIENT_SECRET = env.AUTH_APP_CLIENT_SECRET;

export {
    AWS_REGION,
    AWS_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY,
    AWS_ASSUME_ROLE_ARN,
    AUTO_DESTROY_INACTIVITY_THRESHOLD_MIN,
    PORT,
    AUTH_APP_CLIENT_ID,
    AUTH_APP_CLIENT_SECRET,
    AUTH_URL,
};
