const { env } = process
const PORT = env.PORT || 3000

const AWS_REGION = env.AWS_REGION || 'us-east-1'
const AWS_ACCESS_KEY_ID = env.AWS_ACCESS_KEY_ID
const AWS_SECRET_ACCESS_KEY = env.AWS_SECRET_ACCESS_KEY
const AWS_ASSUME_ROLE_ARN = env.AWS_ASSUME_ROLE_ARN

export {
    AWS_REGION,
    AWS_ACCESS_KEY_ID,
    AWS_SECRET_ACCESS_KEY,
    AWS_ASSUME_ROLE_ARN,

    PORT,
}